using UnityEngine;
using System.Collections;
using UnityEngine.UI;

public class EndDialogue : MonoBehaviour {

	public Text endText;
	public float interLetterTime;
	public static string endTest1,endTest2,endTest3;


	 //endTest="YOU HAVE FINISHED THE GAME.";

	void Start () {
		
		//Kick door, emp camera, knock out man, any escape
		if (StatsManager.knockOutMan && !StatsManager.pickDoor && StatsManager.empCamera) {
			endTest1 = "THE OPERATION LAST NIGHT WENT WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT DIDN'T KILL ANYBODY" +
				" AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. " +
				" HOWEVER, BECAUSE THE AGENT KICKED THE DOOR IN BEFORE DISABLING THE CAMERA, THE GANG KNEW SOMEONE WAS THERE AND HAVE NOW GONE IN HIDING OUT OF FEAR." +
				" THE MISSION WAS A SUCCESS, BUT NOW WE MUST FOCUS ON THE NEXT OBJECTIVE: FIND THIS GANG, AND PUT THEM DOWN FOR GOOD.";
		}
		//Kick door, emp camera, kill man, escape swimming
		if (StatsManager.killMan && !StatsManager.pickDoor && StatsManager.empCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DISALBED THE ONLY CAMERA, THE GANG DIDN'T" +
				" REALIZE WHAT HAPPENED, AND THE DATA WAS EFFECTIVELY DESTROYED. HOWEVER, OUR AGENT KILLED THE ONE MAN IN THE BUILDING, AND SO THE POLICE GOT INVOLVED." +
				" WE ALSO LEARNED THAT, BECAUSE THE AGENT KICKED THE DOOR IN BEFORE DISABLING THE CAMERA, THE GANG KNEW SOMEONE WAS THERE AND HAVE NOW GONE IN HIDING OUT OF FEAR." +
				" BECAUSE "+StatsManager.playerName+" ESCAPED BY SWIMMING, OUR AGENT WAS NOT SPOTTED, BUT A MANHUNT IS CURRENTLY GOING ON TO FIND THEM." +
				" AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE HAD TO DENY ANY CONNECTION TO THEM. THE MISSION WAS A SUCCESS, BUT OUR AGENT IS MIA.";
		}
		//Kick door, emp camera, kill man, escape on foot
		if (StatsManager.killMan && !StatsManager.pickDoor && StatsManager.empCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DISALBED THE ONLY CAMERA, THE GANG DIDN'T" +
				" REALIZE WHAT HAPPENED, AND THE DATA WAS EFFECTIVELY DESTROYED. HOWEVER, OUR AGENT KILLED THE ONE MAN IN THE BUILDING, AND SO THE POLICE GOT INVOLVED." +
				" WE ALSO LEARNED THAT, BECAUSE THE AGENT KICKED THE DOOR IN BEFORE DISABLING THE CAMERA, THE GANG KNEW SOMEONE WAS THERE AND HAVE NOW GONE IN HIDING OUT OF FEAR." +
				" BECAUSE "+StatsManager.playerName+" TRIED TO ESCAPE ON FOOT, OUR AGENT WAS SPOTTED." +
				" AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE HAD TO DENY ANY CONNECTION TO THEM. THE MISSION WAS A SUCCESS, BUT OUR AGENT IS NOW IN JAIL.";
		}
		//Kick door, emp camera, kill man, call in helicopter
		if (StatsManager.killMan && !StatsManager.pickDoor && StatsManager.empCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DISALBED THE ONLY CAMERA, THE GANG DIDN'T" +
				" REALIZE WHAT HAPPENED, AND THE DATA WAS EFFECTIVELY DESTROYED. HOWEVER, OUR AGENT KILLED THE ONE MAN IN THE BUILDING, AND SO THE POLICE GOT INVOLVED." +
				" WE ALSO LEARNED THAT, BECAUSE THE AGENT KICKED THE DOOR IN BEFORE DISABLING THE CAMERA, THE GANG KNEW SOMEONE WAS THERE AND HAVE NOW GONE IN HIDING OUT OF FEAR." +
				" BECAUSE "+StatsManager.playerName+" TRIED TO CALL IN THE EXCTRACTION HELICOPTER, OUR AGENT AND THE PILOT WERE SPOTTED." +
				" AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE HAD TO TURN " + 
				StatsManager.playerName+" OVER TO AUTHORITIES AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A SUCCESS, BUT OUR AGENT IS NOW IN JAIL.";
		}
		//Kick door, emp camera, sneak past man, escape on foot or swim
		if (!StatsManager.knockOutMan && !StatsManager.killMan && !StatsManager.pickDoor && StatsManager.empCamera && (StatsManager.footEscape || StatsManager.swimEscape)) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DISALBED THE ONLY CAMERA AND DIDN'T DEAL WITH THE MAN, THE GANG DIDN'T" +
				" REALIZE WHAT HAPPENED. HOWEVER, THE ONE MAN IN THE BUILDING WAS ABLE TO STOP THE VIRUS." +
				" WE ALSO LEARNED THAT, BECAUSE THE AGENT KICKED THE DOOR IN BEFORE DISABLING THE CAMERA, THE GANG KNEW SOMEONE WAS THERE AND HAVE NOW GONE IN HIDING OUT OF FEAR." +
				" BECAUSE "+StatsManager.playerName+" WAS ABLE TO QUIETLY ESCAPE, OUR AGENT WAS NOT SPOTTED." +
				" AS A RESULT OF NECCESSARY PRECAUTIONS, HOWEVER, WE HAVE HAD TO FIRE " + 
				StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Kick door, emp camera, sneak past man, call in helicopter
		if (!StatsManager.knockOutMan && !StatsManager.killMan && !StatsManager.pickDoor && StatsManager.empCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DISALBED THE ONLY CAMERA AND DIDN'T DEAL WITH THE MAN, THE GANG DIDN'T" +
				" TAKE NOTICE. HOWEVER, THE ONE MAN IN THE BUILDING WAS ABLE TO STOP THE VIRUS." +
				" WE ALSO LEARNED THAT, BECAUSE THE AGENT KICKED THE DOOR IN BEFORE DISABLING THE CAMERA, THE GANG KNEW SOMEONE WAS THERE AND HAVE NOW GONE IN HIDING OUT OF FEAR." +
				" BECAUSE "+StatsManager.playerName+" TRIED TO CALL IN THE EXCTRACTION HELICOPTER, OUR AGENT AND THE PILOT WERE SPOTTED." +
				" AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE HAD TO FIRE " + 
				StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Pick OR kick door, ignore camera, sneak past man, call in helicopter
		if (!StatsManager.knockOutMan && !StatsManager.killMan && !StatsManager.shootCamera && !StatsManager.empCamera && !StatsManager.footEscape && !StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT MISSED A CAMERA AND DIDN'T DEAL WITH THE MAN, NOT ONLY DID THE GANG " +
				" TAKE NOTICE AND SEND MORE MEN OVER TO INVESTIGATE, BUT THE ONE MAN IN THE BUILDING WAS ABLE TO STOP THE VIRUS." +
				" BECAUSE "+StatsManager.playerName+" TRIED TO CALL IN THE EXCTRACTION HELICOPTER, OUR AGENT AND THE PILOT WERE SHOT DOWN." +
				" THE MISSION WAS A FAILURE, AND OUR AGENT IS NOW DEAD.";
		}
		//Pick OR kick door, ignore camera, sneak past man, escape on foot
		if (!StatsManager.knockOutMan && !StatsManager.killMan && !StatsManager.shootCamera && !StatsManager.empCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT MISSED A CAMERA AND DIDN'T DEAL WITH THE MAN, NOT ONLY DID THE GANG " +
				" TAKE NOTICE AND SEND MORE MEN OVER TO INVESTIGATE, BUT THE ONE MAN IN THE BUILDING WAS ABLE TO STOP THE VIRUS." +
				" BECAUSE "+StatsManager.playerName+" TRIED TO ESCAPE BY FOOT, OUR AGENT WAS EVENTUALLY SPOTTED AND KILLED." +
				" THE MISSION WAS A FAILURE, AND OUR AGENT IS NOW DEAD.";
		}
		//Pick OR kick door, ignore camera, sneak past man, escape swimming
		if (!StatsManager.knockOutMan && !StatsManager.killMan && !StatsManager.shootCamera && !StatsManager.empCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT MISSED A CAMERA AND DIDN'T DEAL WITH THE MAN, NOT ONLY DID THE GANG " +
				" TAKE NOTICE AND SEND MORE MEN OVER TO INVESTIGATE, BUT THE ONE MAN IN THE BUILDING WAS ABLE TO STOP THE VIRUS." +
				" BECAUSE "+StatsManager.playerName+" ESCAPED BY SWIMMING, OUR AGENT WAS NOT SPOTTED, BUT IS NOW BEING MANHUNTED . AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND OUR AGENT IS MIA.";
		}
		//Pick OR kick door, ignore camera, kill man, escape on foot
		if (!StatsManager.knockOutMan && StatsManager.killMan && !StatsManager.shootCamera && !StatsManager.empCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT KILLED SOMEONE, POLICE GOT INVOLVED AND HAVE EVIDENCE POINTING TO THEM." +
				" ALSO, IT SEEMS "+StatsManager.playerName + " MISSED A CAMERA, BECAUSE THE GANG TOOK NOTICE AND" +
				" WAS ABLE TO REMOTELY GRAB SOME OF THE DATA BEFORE OUR AGENT GOT TO IT. BECAUSE "+StatsManager.playerName+" TRIED TO ESCAPE ON FOOT," +
				" OUR AGENT WAS SPOTTED BY THE POLICE. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND OUR AGENT IS IN JAIL.";
		}
		//Pick OR kick door, ignore camera, kill man, call in helicopter
		if (!StatsManager.knockOutMan && StatsManager.killMan && !StatsManager.shootCamera && !StatsManager.empCamera && !StatsManager.footEscape && !StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT KILLED SOMEONE, POLICE GOT INVOLVED AND HAVE EVIDENCE POINTING TO THEM." +
				" ALSO, IT SEEMS "+StatsManager.playerName + " MISSED A CAMERA, BECAUSE THE GANG TOOK NOTICE AND" +
				" REMOTELY GRABBED THE DATA BEFORE OUR AGENT GOT TO IT. BECAUSE "+StatsManager.playerName+" CALLED IN THE HELICOPTER " +
				" TO THE BUILDING TO EXTRACT HIM, OUR HELICOPTER WAS SPOTTED BY A FEW MEMBERS OF THE GANG THAT WERE SENT TO INVESTIGATE, AS WELL AS THE POLICE. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO TURN "+StatsManager.playerName+" OVER TO AUTHORITIES AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND OUR AGENT IS IN JAIL.";
		}
		//Pick OR kick door, ignore camera, kill man, escape swimming
		if (!StatsManager.knockOutMan && StatsManager.killMan && !StatsManager.shootCamera && !StatsManager.empCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT KILLED SOMEONE, POLICE GOT INVOLVED AND HAVE EVIDENCE POINTING TO THEM." +
				" ALSO, IT SEEMS "+StatsManager.playerName + " MISSED A CAMERA, BECAUSE THE GANG TOOK NOTICE AND" +
				" REMOTELY GRABBED THE DATA BEFORE OUR AGENT GOT TO IT. BECAUSE "+StatsManager.playerName+" SWAM IN THE RIVER TO AVOID DETECTION," +
				" OUR AGENT WAS NOT SPOTTED BY ANYONE, BUT IS CURRENTLY BEING MANHUNTED BY BOTH THE GANG AND THE POLICE. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND OUR AGENT IS MIA.";
		}
		//Pick OR kick door, ignore camera, knock out man, call in helicopter
		if (StatsManager.knockOutMan && !StatsManager.empCamera &&!StatsManager.shootCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO SO SMOOTHLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYONE, NO TRACES INITIALLY WERE FOUND LEADING TO US." +
				" BUT IT SEEMS "+StatsManager.playerName + " MISSED A CAMERA, BECAUSE THE GANG TOOK NOTICE AND" +
				" WAS ABLE TO REMOTELY GRAB SOME OF THE DATA BEFORE OUR AGENT GOT TO IT. BECAUSE "+StatsManager.playerName+" CALLED IN THE HELICOPTER " +
				" TO THE BUILDING TO EXTRACT THEM, OUR HELICOPTER WAS SPOTTED BY A FEW MEMBERS OF THE GANG THAT WERE SENT TO INVESTIGATE. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO FIRE "+StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Pick OR kick door, ignore camera, knock out man, escape on foot
		if (StatsManager.knockOutMan && !StatsManager.empCamera &&!StatsManager.shootCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO SO SMOOTHLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYONE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT IT SEEMS "+StatsManager.playerName + " MISSED A CAMERA, BECAUSE THE GANG TOOK NOTICE AND" +
				" REMOTELY GRABBED THE DATA BEFORE OUR AGENT GOT TO IT.  THE MISSION WAS A FAILURE.";
		}
		//Pick OR kick door, ignore camera, knock out man, escape swimming
		if (StatsManager.knockOutMan && !StatsManager.empCamera &&!StatsManager.shootCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO SO SMOOTHLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYONE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT IT SEEMS "+StatsManager.playerName + " MISSED A CAMERA, BECAUSE THE GANG TOOK NOTICE AND" +
				" REMOTELY GRABBED THE DATA BEFORE OUR AGENT GOT TO IT.  THE MISSION WAS A FAILURE.";
		}
		//Pick OR kick door, shoot camera, knock out man, any escape
		if (StatsManager.knockOutMan && StatsManager.shootCamera) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYONE AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName + " SHOT A CAMERA, THE GANG TOOK NOTICE AND" +
				" REMOTELY GRABBED THE DATA BEFORE OUR AGENT GOT TO IT.  THE MISSION WAS A FAILURE.";
		}
		//Pick OR kick door, shoot camera, kill man, any escape
		if (StatsManager.killMan && StatsManager.shootCamera) {
			endTest1 = "THE OPERATION LAST NIGHT DIDN'T GO WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " KILLED THE ONE MAN IN THE BUILDING,"+
				" THE POLICE GOT INVOLVED, AND THEY LEFT EVIDENCE LEADING BACK TO THEM. WE ALSO FOUND OUT LATER ON THAT" +
				" A CAMERA WAS SHOT, AND AS A FAILSAFE THE GANG REMOTELY GRABBED THE DATA BEFORE OUR AGENT GOT TO IT. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO FIRE "+StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Pick OR kick door, shoot camera, sneak past man, escape on foot
		if (!StatsManager.knockOutMan && !StatsManager.killMan && StatsManager.shootCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYBODY AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " DIDN'T DEAL WITH THE ONE MAN IN THE BUILDING,"+
				" HE WAS ABLE TO STOP THE VIRUS BEFORE IT COULD FINISH. WE ALSO FOUND OUT LATER ON THAT" +
				" A BULLET WAS FOUND, LEADING BACK TO OUR AGENT. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO FIRE "+StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Pick OR kick door, shoot camera, sneak past man, escape swimming
		if (!StatsManager.knockOutMan && !StatsManager.killMan && StatsManager.shootCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYBODY AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " DIDN'T DEAL WITH THE ONE MAN IN THE BUILDING,"+
				" HE WAS ABLE TO STOP THE VIRUS BEFORE IT COULD FINISH. WE ALSO FOUND OUT LATER ON THAT" +
				" A BULLET WAS FOUND, LEADING BACK TO OUR AGENT. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO FIRE "+StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Pick OR kick door, shoot camera, sneak past man, call in helicopter
		if (!StatsManager.knockOutMan && !StatsManager.killMan && StatsManager.shootCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYBODY AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " DIDN'T DEAL WITH THE ONE MAN IN THE BUILDING,"+
				" HE WAS ABLE TO STOP THE VIRUS BEFORE IT COULD FINISH. WE ALSO FOUND OUT LATER ON THAT" +
				" A BULLET WAS FOUND, LEADING BACK TO OUR AGENT. ON TOP OF ALL THIS, OUR HELICOPTER WAS ALSO SPOTTED, LEAVING MORE POSSIBLE TRACES TO US. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" + 
				" HAD TO FIRE "+StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A FAILURE, AND WE LOST ONE OF OUR BEST.";
		}
		//Pick door, emp camera, kill man, escape swimming
		if (StatsManager.killMan && StatsManager.pickDoor && StatsManager.empCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT" +
				" DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. HOWEVER, BECAUSE "+StatsManager.playerName+ " KILLED THE ONE MAN IN THE BUILDING,"+
				" THE POLICE GOT INVOLVED, AND THEY LEFT EVIDENCE LEADING BACK TO THEM. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" +
				" HAD TO FIRE "+StatsManager.playerName+" AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A SUCCESS, BUT WE LOST ONE OF OUR BEST.";
		}
		//Pick door, emp camera, kill man, escape on foot
		if (StatsManager.killMan && StatsManager.pickDoor && StatsManager.empCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT" +
				" DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. HOWEVER, BECAUSE "+StatsManager.playerName+ " KILLED THE ONE MAN IN THE BUILDING,"+
				" THE POLICE GOT INVOLVED, AND THEY LEFT EVIDENCE LEADING BACK TO THEM. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" +
				" HAD TO TURN "+StatsManager.playerName+" OVER TO AUTHORITIES AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A SUCCESS, BUT OUR AGENT IS IN JAIL.";
		}
		//Pick door, emp camera, kill man, call in helicopter
		if (StatsManager.killMan && StatsManager.pickDoor && StatsManager.empCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT" +
				" DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. HOWEVER, BECAUSE "+StatsManager.playerName+ " KILLED THE ONE MAN IN THE BUILDING,"+
				" THE POLICE GOT INVOLVED, AND THEY LEFT EVIDENCE LEADING BACK TO THEM. AS A RESULT OF NECCESSARY PRECAUTIONS, WE HAVE" +
				" HAD TO TURN "+StatsManager.playerName+" OVER TO AUTHORITIES AND DENY ANY CONNECTION TO THEM. THE MISSION WAS A SUCCESS, BUT OUR AGENT IS IN JAIL.";
		}
		//Pick door, emp camera, sneak past man, escape on foot
		if (!StatsManager.knockOutMan && !StatsManager.killMan && StatsManager.pickDoor && StatsManager.empCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYBODY AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " DIDN'T DEAL WITH THE ONE MAN IN THE BUILDING,"+
				" HE WAS ABLE TO STOP THE VIRUS BEFORE IT COULD FINISH. THE MISSION WAS A FAILURE.";
		}
		//Pick door, emp camera, sneak past man, escape swimming
		if (!StatsManager.knockOutMan && !StatsManager.killMan && StatsManager.pickDoor && StatsManager.empCamera && StatsManager.swimEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYBODY AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " DIDN'T DEAL WITH THE ONE MAN IN THE BUILDING,"+
				" HE WAS ABLE TO STOP THE VIRUS BEFORE IT COULD FINISH. THE MISSION WAS A FAILURE.";
		}
		//Pick door, emp camera, sneak past man, call in helicopter
		if (!StatsManager.knockOutMan && !StatsManager.killMan && StatsManager.pickDoor && StatsManager.empCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT ALMOST WENT PERFECTLY. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. OR SO WE THOUGHT." +
				" BECAUSE OUR AGENT DIDN'T KILL ANYBODY AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. BUT BECAUSE "+StatsManager.playerName+ " DIDN'T DEAL WITH THE ONE MAN IN THE BUILDING,"+
				" HE WAS ABLE TO STOP THE VIRUS BEFORE IT COULD FINISH. THE MISSION WAS A FAILURE.";
		}
		//Pick door, emp camera, knock out man, escape on foot
		if (StatsManager.knockOutMan && StatsManager.pickDoor && StatsManager.empCamera && StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT WENT WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT DIDN'T KILL ANYBODY" +
				" AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. THE MISSION WAS A SUCCESS.";
		}
		//Pick door, emp camera, knock out man, call in helicopter
		if (StatsManager.knockOutMan && StatsManager.pickDoor && StatsManager.empCamera && !StatsManager.swimEscape && !StatsManager.footEscape) {
			endTest1 = "THE OPERATION LAST NIGHT WENT WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT DIDN'T KILL ANYBODY" +
				" AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. THE MISSION WAS A SUCCESS.";
		}
		//Pick door, emp camera, knock out man, escape swimming
		if (StatsManager.empCamera && StatsManager.knockOutMan && StatsManager.swimEscape && StatsManager.pickDoor) {
			endTest1 = "THE OPERATION LAST NIGHT WENT WELL. AFTER ARRIVING AND GETTING INSIDE, " + StatsManager.playerName +
				" WAS ABLE TO DESTROY THE DATA AND GET OUT WITHOUT INCIDENT. BECAUSE OUR AGENT DIDN'T KILL ANYBODY" +
				" AND DISABLED ANY WAYS IN WHICH THE GANG MIGHT BE WATCHING THE PLACE, NO TRACES WHATSOEVER WERE" +
				" FOUND LEADING TO US. THE MISSION WAS A SUCCESS.";
		}


		StartCoroutine (addText (endTest1+endTest2));
	}
	
	IEnumerator addText(string text){
		int textLength=text.Length;
		for (int i = 0; i <= textLength; i++) {
			endText.text = text.Substring (0, i);
			yield return new WaitForSeconds (interLetterTime);
		}
	}
}
